packages:
  - docs
  - package/*
  - play/*

catalog:
  '@rollup/plugin-commonjs': ^25.0.7
  '@rollup/plugin-node-resolve': ^15.2.3
  '@rollup/plugin-terser': ^0.4.4
  '@rollup/plugin-typescript': ^11.1.5
  '@types/markdown-it': ^12.2.3
  '@types/node': ^20.10.3
  rollup: ^4.6.0
  tslib: ^2.6.2
  typescript: ^5.2.2
  vite: ^6.0.1
  gh-pages: ^6.1.0
  vitepress: 1.0.0-rc.31
  
catalogs:
  vue3:
    '@vitejs/plugin-vue': ^5.0.0
    '@vue/compiler-sfc': ^3.3.9
    vue: ^3.3.4
  react18:
    '@vitejs/plugin-react': ^4.3.4
    '@types/react': ^18.2.0
    '@types/react-dom': ^18.2.0
    react: ^18.2.0
    react-dom: ^18.2.0
  react19:
    '@vitejs/plugin-react': ^4.3.4
    '@types/react': ^19.0.0
    '@types/react-dom': ^19.0.0
    react: ^19.0.0
    react-dom: ^19.0.0